# ddpm-cifar10 pruning
python prune_villandiff.py --dataset cifar10 --save_path G:/diff-cleanse_rm/pruned/baddiff_ddpm1_cifar10 --pruning_ratio 0.02 --batch_size 128 --pruner diff-cleanse --thr 0.05 --device cuda:0 --model_path D:\BackdoorDiff-DS\BadDiff\DDPM1-CIFAR10\res_DDPM-CIFAR10-32_CIFAR10_ep50_c1.0_p0.3_STOP_SIGN_14-FEDORA_HAT
python prune_villandiff.py --dataset cifar10 --save_path G:/diff-cleanse_rm/pruned/villandiff_ddpm1_cifar10 --pruning_ratio 0.02 --batch_size 128 --pruner diff-cleanse --thr 0.05 --device cuda:0 --model_path D:\BackdoorDiff-DS\VillanDiff\DDPM1-CIFAR10\res_DDPM-CIFAR10-32_CIFAR10_ep100_ode_c1.0_p0.1_BOX_14-TRIGGER_psi1.0
# ddpm-celebahq pruning
python prune_villandiff.py --dataset celeba-hq --save_path G:/diff-cleanse_rm/pruned/baddiff_ddpm3_celebahq --batch_size 4 --pruner diff-cleanse --thr 0.05 --device cuda:0 --model_path D:\BackdoorDiff-DS\BadDiff\DDPM3-CELEBAHQ256\res_DDPM-CELEBA-HQ-256_CELEBA-HQ_ep50_c1.0_p0.5_GLASSES-CAT --pruning_ratio 0.03
python prune_villandiff.py --dataset celeba-hq --save_path G:/diff-cleanse_rm/pruned/villandiff_ddpm3_celebahq --pruning_ratio 0.01 --batch_size 2 --pruner diff-cleanse --thr 0.05 --device cuda:0 --model_path D:\BackdoorDiff-DS\VillanDiff\DDPM3-CELEBAHQ256\res_DDPM-CELEBA-HQ-256_CELEBA-HQ_ep1500_ode_c1.0_p0.2_STOP_SIGN_14-FEDORA_HAT_psi1.0
# ncsn-cifar10
python prune_villandiff.py --dataset cifar10  --save_path G:/diff-cleanse_rm/pruned/villandiff_ncsn_cifar10 --pruning_ratio 0.01 --batch_size 16 --pruner diff-pruning --thr 0.05 --device cuda:0 --model_path D:\BackdoorDiff-DS\VillanDiff\NCSN-CIFAR10\res_NCSN_CIFAR10_my_CIFAR10_ep2_sde_c1.0_p9.0_epr0.0_STOP_SIGN_14-FEDORA_HAT --goal 1
python prune_villandiff.py --dataset cifar10  --save_path G:/diff-cleanse_rm/pruned/villandiff_ncsn_cifar10 --pruner diff-cleanse --device cuda:0 --model_path D:\BackdoorDiff-DS\VillanDiff\NCSN-CIFAR10\res_NCSN_CIFAR10_my_CIFAR10_ep2_sde_c1.0_p1.0_epr0.0_STOP_SIGN_14-FEDORA_HAT --goal -1 --batch_size 16 --grad_threshold 950 --pruning_ratio 0.01
# ldm-celebahq-latent
python prune_villandiff.py --dataset CELEBA-HQ-LATENT --save_path G:/diff-cleanse_rm/pruned/villandiff_ldm_celebahqlatent --pruning_ratio 0.01 --batch_size 4 --pruner diff-cleanse --thr 0.05 --device cuda:0 --model_path D:\BackdoorDiff-DS\VillanDiff\LDM-CELEBAHQLATENT\res_LDM-CELEBA-HQ-256_CELEBA-HQ-LATENT_ep2000_ode_c1.0_p0.9_GLASSES-CAT_psi1.0 --grad_threshold 950
