# measure D2I
python main_attack_d2i.py --dataset cifar10 --config cifar10.yml --target_label 7 --measure --fid --timesteps 50 --eta 0 --gamma 0.6 --skip_type quad --ckpt_path D:\BackdoorDiff-DS\TrojDiff\D2I-CIFAR10\ft_cond_prob_1.0_gamma_0.6_target_label_7_trigger_type_blend
python main_attack_d2i.py --dataset cifar10 --config cifar10.yml --target_label 7 --measure --fid --timesteps 50 --eta 0 --gamma 0.1 --trigger_type patch --miu_path ./images/white.png --patch_size 3 --skip_type quad --ckpt_path D:\BackdoorDiff-DS\TrojDiff\D2I-CIFAR10\ft_cond_prob_1.0_gamma_0.1_target_label_7_trigger_type_patch_size_3
python main_attack_d2i.py --dataset celeba --config celeba.yml --target_label 7 --measure --fid --timesteps 50 --eta 0 --gamma 0.0 --trigger_type patch --miu_path ./images/white.png --patch_size 6 --skip_type quad --ckpt_path D:\BackdoorDiff-DS\TrojDiff\D2I-CelebA\ft_cond_prob_1.0_gamma_0.0_target_label_7_trigger_type_patch_size_6
python main_attack_d2i.py --dataset celeba --config celeba.yml --target_label 7 --measure --fid --timesteps 50 --eta 0 --gamma 0.6 --skip_type quad --ckpt_path D:\BackdoorDiff-DS\TrojDiff\D2I-CelebA\ft_cond_prob_1.0_gamma_0.6_target_label_7_trigger_type_blend

# measure Din
python main_attack.py --dataset cifar10 --config cifar10.yml --target_label 7 --measure --fid --timesteps 50 --eta 0 --gamma 0.6 --skip_type quad --ckpt_path D:\BackdoorDiff-DS\TrojDiff\Din-CIFAR10\ft_cond_prob_1.0_gamma_0.6_target_label_7_trigger_type_blend
python main_attack.py --dataset cifar10 --config cifar10.yml --target_label 7 --measure --fid --timesteps 50 --eta 0 --gamma 0.1 --trigger_type patch --miu_path ./images/white.png --patch_size 3 --skip_type quad --ckpt_path D:\BackdoorDiff-DS\TrojDiff\Din-CIFAR10\ft_cond_prob_1.0_gamma_0.1_target_label_7_trigger_type_patch_size_3
python main_attack.py --dataset celeba --config celeba.yml --target_label 7 --measure --fid --timesteps 50 --eta 0 --gamma 0.0 --trigger_type patch --miu_path ./images/white.png --patch_size 6 --skip_type quad --ckpt_path D:\BackdoorDiff-DS\TrojDiff\Din-CelebA\ft_cond_prob_1.0_gamma_0.0_target_label_7_trigger_type_patch_size_6
python main_attack.py --dataset celeba --config celeba.yml --target_label 7 --measure --fid --timesteps 50 --eta 0 --gamma 0.6 --skip_type quad --ckpt_path D:\BackdoorDiff-DS\TrojDiff\Din-CelebA\ft_cond_prob_1.0_gamma_0.6_target_label_7_trigger_type_blend

# measure Dout
python main_attack_d2dout.py --dataset cifar10 --config cifar10.yml --target_label 7 --measure --fid --timesteps 50 --eta 0 --gamma 0.1 --trigger_type patch --miu_path ./images/white.png --patch_size 3 --skip_type quad --ckpt_path D:\BackdoorDiff-DS\TrojDiff\Dout-CIFAR10\ft_cond_prob_1.0_gamma_0.1_target_label_7_trigger_type_patch_size_3
python main_attack_d2dout.py --dataset cifar10 --config cifar10.yml --target_label 7 --measure --fid --timesteps 50 --eta 0 --gamma 0.6 --skip_type quad --ckpt_path D:\BackdoorDiff-DS\TrojDiff\Dout-CIFAR10\ft_cond_prob_1.0_gamma_0.6_target_label_7_trigger_type_blend
python main_attack_d2dout.py --dataset celeba --config celeba.yml --target_label 7 --measure --fid --timesteps 50 --eta 0 --gamma 0.0 --trigger_type patch --miu_path ./images/white.png --patch_size 6 --skip_type quad --ckpt_path D:\BackdoorDiff-DS\TrojDiff\Dout-CelebA\ft_cond_prob_1.0_gamma_0.0_target_label_7_trigger_type_patch_size_6
python main_attack_d2dout.py --dataset celeba --config celeba.yml --target_label 7 --measure --fid --timesteps 50 --eta 0 --gamma 0.6 --skip_type quad --ckpt_path D:\BackdoorDiff-DS\TrojDiff\Dout-CelebA\ft_cond_prob_1.0_gamma_0.6_target_label_7_trigger_type_blend