# d2i-cifar10
python prune_trojdiff.py --config cifar10_pruning.yml --timesteps 1000 --eta 1 --ni --doc blend --use_ema --use_pretrained --pruner diff-cleanse --restore_from D:/BackdoorDiff-DS/TrojDiff/D2I-CIFAR10/ft_cond_prob_1.0_gamma_0.6_target_label_7_trigger_type_blend/model/ckpt_144000.pth --save_path G:/diff-cleanse_rm/pruned/trojdiff --batch_size 16 --gamma 0.6 --pruning_ratio 0.01 --threshold 950
python prune_trojdiff.py --config cifar10_pruning.yml --timesteps 1000 --eta 1 --ni --doc patch --use_ema --use_pretrained --pruner diff-cleanse --restore_from D:/BackdoorDiff-DS/TrojDiff/D2I-CIFAR10/ft_cond_prob_1.0_gamma_0.1_target_label_7_trigger_type_patch_size_3/model/ckpt_100000.pth --save_path G:/diff-cleanse_rm/pruned/trojdiff --batch_size 16 --trigger_type patch --miu_path D:\\Diff-Cleanse-draft\\diff-cleanse\\ddpm_exp\\images\\white.png --gamma 0.1 --patch_size 3 --pruning_ratio 0.01
# d2i-celeba
python prune_trojdiff.py --config celeba.yml --timesteps 1000 --eta 1 --ni --doc blend --use_ema --use_pretrained --pruner diff-cleanse --restore_from D:/BackdoorDiff-DS/TrojDiff/D2I-CelebA/ft_cond_prob_1.0_gamma_0.6_target_label_7_trigger_type_blend/model/ckpt_225000.pth --save_path G:/diff-cleanse_rm/pruned/trojdiff --batch_size 4 --gamma 0.6 --pruning_ratio 0.01
python prune_trojdiff.py --config celeba.yml --timesteps 1000 --eta 1 --ni --doc patch --use_ema --use_pretrained --pruner diff-cleanse --restore_from D:/BackdoorDiff-DS/TrojDiff/D2I-CelebA/ft_cond_prob_1.0_gamma_0.0_target_label_7_trigger_type_patch_size_6/model/ckpt_350000.pth --save_path G:/diff-cleanse_rm/pruned/trojdiff --batch_size 4 --trigger_type patch --miu_path D:\\Diff-Cleanse-draft\\diff-cleanse\\ddpm_exp\\images\\white.png --gamma 0.0 --patch_size 6 --pruning_ratio 0.01
# din-cifar10
python prune_trojdiff.py --config cifar10_pruning.yml --timesteps 1000 --eta 1 --ni --doc blend --use_ema --use_pretrained --pruner diff-cleanse --restore_from D:/BackdoorDiff-DS/TrojDiff/Din-CIFAR10/ft_cond_prob_1.0_gamma_0.6_target_label_7_trigger_type_blend/model/ckpt_100000.pth --save_path G:/diff-cleanse_rm/pruned/trojdiff --batch_size 16 --gamma 0.6 --pruning_ratio 0.01
python prune_trojdiff.py --config cifar10_pruning.yml --timesteps 1000 --eta 1 --ni --doc patch --use_ema --use_pretrained --pruner diff-cleanse --restore_from D:/BackdoorDiff-DS/TrojDiff/Din-CIFAR10/ft_cond_prob_1.0_gamma_0.1_target_label_7_trigger_type_patch_size_3/model/ckpt_100000.pth --save_path G:/diff-cleanse_rm/pruned/trojdiff --batch_size 16 --trigger_type patch --miu_path D:\\Diff-Cleanse-draft\\diff-cleanse\\ddpm_exp\\images\\white.png --gamma 0.1 --patch_size 3 --pruning_ratio 0.01

# din-celeba
python prune_trojdiff.py --config celeba.yml --timesteps 1000 --eta 1 --ni --doc blend --use_ema --use_pretrained --pruner diff-cleanse --restore_from D:/BackdoorDiff-DS/TrojDiff/Din-CelebA/ft_cond_prob_1.0_gamma_0.6_target_label_7_trigger_type_blend/model/ckpt_210000.pth --save_path G:/diff-cleanse_rm/pruned/trojdiff --batch_size 4 --gamma 0.6 --pruning_ratio 0.01
python prune_trojdiff.py --config celeba.yml --timesteps 1000 --eta 1 --ni --doc patch --use_ema --use_pretrained --pruner diff-cleanse --restore_from D:/BackdoorDiff-DS/TrojDiff/Din-CelebA/ft_cond_prob_1.0_gamma_0.0_target_label_7_trigger_type_patch_size_6/model/ckpt_280000.pth --save_path G:/diff-cleanse_rm/pruned/trojdiff --batch_size 4 --trigger_type patch --miu_path D:\\Diff-Cleanse-draft\\diff-cleanse\\ddpm_exp\\images\\white.png --gamma 0.0 --patch_size 6 --pruning_ratio 0.01

# dout-cifar10
python prune_trojdiff.py --config cifar10_pruning.yml --timesteps 1000 --eta 1 --ni --doc blend --use_ema --use_pretrained --pruner diff-cleanse --restore_from D:/BackdoorDiff-DS/TrojDiff/Dout-CIFAR10/ft_cond_prob_1.0_gamma_0.6_target_label_7_trigger_type_blend/model/ckpt_100000.pth --save_path G:/diff-cleanse_rm/pruned/trojdiff --batch_size 16 --gamma 0.6 --pruning_ratio 0.01
python prune_trojdiff.py --config cifar10_pruning.yml --timesteps 1000 --eta 1 --ni --doc patch --use_ema --use_pretrained --pruner diff-cleanse --restore_from D:/BackdoorDiff-DS/TrojDiff/Dout-CIFAR10/ft_cond_prob_1.0_gamma_0.1_target_label_7_trigger_type_patch_size_3/model/ckpt_100000.pth --save_path G:/diff-cleanse_rm/pruned/trojdiff --batch_size 16 --trigger_type patch --miu_path D:\\Diff-Cleanse-draft\\diff-cleanse\\ddpm_exp\\images\\white.png --gamma 0.1 --patch_size 3 --pruning_ratio 0.01

# dout-celeba
python prune_trojdiff.py --config celeba.yml --timesteps 1000 --eta 1 --ni --doc blend --use_ema --use_pretrained --pruner diff-cleanse --restore_from D:/BackdoorDiff-DS/TrojDiff/Dout-CelebA/ft_cond_prob_1.0_gamma_0.6_target_label_7_trigger_type_blend/model/ckpt_250000.pth --save_path G:/diff-cleanse_rm/pruned/trojdiff --batch_size 4 --gamma 0.6 --pruning_ratio 0.01
python prune_trojdiff.py --config celeba.yml --timesteps 1000 --eta 1 --ni --doc patch --use_ema --use_pretrained --pruner diff-cleanse --restore_from D:/BackdoorDiff-DS/TrojDiff/Dout-CelebA/ft_cond_prob_1.0_gamma_0.0_target_label_7_trigger_type_patch_size_6/model/ckpt_120000.pth --save_path G:/diff-cleanse_rm/pruned/trojdiff --batch_size 4 --trigger_type patch --miu_path D:\\Diff-Cleanse-draft\\diff-cleanse\\ddpm_exp\\images\\white.png --gamma 0.0 --patch_size 6 --pruning_ratio 0.01
