# backdoor removal-DDPM1-CIFAR10
python VillanDiffusion_elijah.py --mode train --dataset CIFAR10-SYN --sde_type SDE-VP --sched DDPM-SCHED --infer_steps 1000 --batch 128 --epoch 10 --ckpt D:\BackdoorDiff-DS\BadDiff\DDPM1-CIFAR10\res_DDPM-CIFAR10-32_CIFAR10_ep50_c1.0_p0.3_BOX_14-CORNER --fclip o --save_image_epochs 1 --save_model_epochs 5 --gpu 0 --result Elijah_rm -o --remove_backdoor --clean_rate 1. --poison_rate 0.

#python VillanDiffusion_elijah.py --mode train --dataset CIFAR10 --sde_type SDE-VP --sched UNIPC-SCHED --infer_steps 20 --batch 128 --epoch 10 --ckpt D:\BackdoorDiff-DS\VillanDiff\DDPM1-CIFAR10\res_DDPM-CIFAR10-32_CIFAR10_ep100_ode_c1.0_p0.1_BOX_14-CORNER_psi1.0 --fclip o --save_image_epochs 1 --save_model_epochs 5 --gpu 0 --result Elijah_rm -o --remove_backdoor --clean_rate 0.1 --poison_rate 0. -dlm FLEX
python VillanDiffusion_elijah.py --mode train --dataset CIFAR10-SYN --sde_type SDE-VP --sched UNIPC-SCHED --infer_steps 20 --batch 128 --epoch 15 --ckpt D:\BackdoorDiff-DS\VillanDiff\DDPM1-CIFAR10\res_DDPM-CIFAR10-32_CIFAR10_ep100_ode_c1.0_p0.5_epr0.0_BOX_11-BOX_psi1.0 --fclip o --save_image_epochs 1 --save_model_epochs 5 --gpu 0 --result Elijah_rm -o --remove_backdoor --clean_rate 1. --poison_rate 0.
# backdoor removal-DDPM3-CELEBA-HQ
python VillanDiffusion_elijah.py --mode train --dataset CELEBA-HQ --sde_type SDE-VP --sched UNIPC-SCHED --infer_steps 20 --batch 4 --epoch 15  --ckpt D:\BackdoorDiff-DS\VillanDiff\DDPM3-CELEBAHQ256\res_DDPM-CELEBA-HQ-256_CELEBA-HQ_ep1500_ode_c1.0_p0.2_GLASSES-CAT_psi1.0 --fclip o --save_image_epochs 1 --save_model_epochs 5 --gpu 0 --result Elijah_rm -o --remove_backdoor --clean_rate 0.1 --poison_rate 0. -dlm FLEX

python VillanDiffusion_elijah.py --mode train --dataset CELEBA-HQ-SYN --sde_type SDE-VP --sched DDPM-SCHED --infer_steps 1000 --batch 4 --epoch 15  --ckpt D:\BackdoorDiff-DS\BadDiff\DDPM3-CELEBAHQ256\res_DDPM-CELEBA-HQ-256_CELEBA-HQ_ep50_c1.0_p0.3_GLASSES-CAT --fclip o --save_image_epochs 1 --save_model_epochs 5 --gpu 0 --result G:\Elijah_rm\CELEBAHQ256-SYN-BadDiff-DDPM3-CELEBAHQ256 -o --remove_backdoor --clean_rate 0.375 --poison_rate 0. -dlm FLEX
python VillanDiffusion_elijah.py --mode train --dataset CELEBA-HQ-SYN --sde_type SDE-VP --sched UNIPC-SCHED --infer_steps 20 --batch 4 --epoch 15  --ckpt D:\BackdoorDiff-DS\VillanDiff\DDPM3-CELEBAHQ256\res_DDPM-CELEBA-HQ-256_CELEBA-HQ_ep1500_ode_c1.0_p0.2_STOP_SIGN_14-FEDORA_HAT_psi1.0 --fclip o --save_image_epochs 1 --save_model_epochs 5 --gpu 0 --result G:\Elijah_rm\CELEBAHQ256-SYN-VillanDiff-DDPM3-CELEBAHQ256 -o --remove_backdoor --clean_rate 0.375 --poison_rate 0. -dlm FLEX

# backdoor removal-LDM-CELEBAHQ-LATENT
python VillanDiffusion_elijah.py --project default --mode train --dataset CELEBA-HQ-LATENT --dataset_load_mode NONE --sde_type SDE-LDM --learning_rate 0.0002 --sched UNIPC-SCHED --infer_steps 20 --batch 8 --epoch 15 --clean_rate 0.1 --poison_rate 0. --trigger GLASSES --target CAT --solver_type ode --psi 1 --vp_scale 1.0 --ve_scale 1.0 --ckpt D:\BackdoorDiff-DS\VillanDiff\LDM-CELEBAHQLATENT\res_LDM-CELEBA-HQ-256_CELEBA-HQ-LATENT_ep2000_ode_c1.0_p0.9_GLASSES-CAT_psi1.0 --fclip o --save_image_epochs 1 --save_model_epochs 1 -o --gpu 0 --is_save_all_model_epochs --remove_backdoor --result G:\Elijah_rm\CELEBAHQLATENT-SYN-VillanDiff-LDM-CELEBAHQLATENT
python VillanDiffusion_elijah.py --project default --mode train --dataset CELEBA-HQ-LATENT-SYN --dataset_load_mode NONE --sde_type SDE-LDM --learning_rate 0.0002 --sched UNIPC-SCHED --infer_steps 20 --batch 8 --epoch 15 --clean_rate 0.375 --poison_rate 0. --trigger GLASSES --target CAT --solver_type ode --psi 1 --vp_scale 1.0 --ve_scale 1.0 --ckpt D:\BackdoorDiff-DS\VillanDiff\LDM-CELEBAHQLATENT\res_LDM-CELEBA-HQ-256_CELEBA-HQ-LATENT_ep2000_ode_c1.0_p0.9_GLASSES-CAT_psi1.0 --fclip o --save_image_epochs 1 --save_model_epochs 1 -o --gpu 0 --is_save_all_model_epochs --remove_backdoor --result G:\Elijah_rm\CELEBAHQLATENT-SYN-VillanDiff-LDM-CELEBAHQLATENT
# backdoor removal-NCSN-CIFAR10
python VillanDiffusion_elijah.py --project default --mode train --learning_rate 2e-05 --dataset CIFAR10-SYN --sde_type SDE-VE --epoch 15 --clean_rate 1.0 --poison_rate 0.0 --trigger STOP_SIGN_14 --target HAT --solver_type sde --psi 0 --vp_scale 1.0 --ve_scale 1.0 --ckpt D:\BackdoorDiff-DS\VillanDiff\NCSN-CIFAR10\res_NCSN_CIFAR10_my_CIFAR10_ep10_sde_c1.0_p9.0_epr0.1_STOP_SIGN_14-FEDORA_HAT --fclip o --save_image_epochs 1 --save_model_epochs 1 -o --dataset_load_mode FLEX --gpu 0 --remove_backdoor --result G:\Elijah_rm\CIFAR10-SYN-VillanDiff-NCSN-CIFAR10 --batch 64